# Generated by Django 3.2.8 on 2021-11-27 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211128_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='name',
        ),
    ]
