# Generated by Django 3.2.8 on 2021-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_place_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
